set_location_assignment PIN_BU28 -to i_fpga_core_resetn
set_location_assignment PIN_BK31 -to i_clk_hvio_6a_100m

set_location_assignment PIN_BW38 -to o_ddr4_comp1_bg[0]
set_location_assignment PIN_CA38 -to o_ddr4_comp1_ba[1]
set_location_assignment PIN_BU38 -to o_ddr4_comp1_ba[0]
set_location_assignment PIN_BR38 -to i_ddr4_comp1_alert_n
set_location_assignment PIN_BU41 -to o_ddr4_comp1_a[16]
set_location_assignment PIN_BR41 -to o_ddr4_comp1_a[15]
set_location_assignment PIN_CA49 -to o_ddr4_comp1_a[14]
set_location_assignment PIN_BW49 -to o_ddr4_comp1_a[13]
set_location_assignment PIN_BU52 -to o_ddr4_comp1_a[12]
set_location_assignment PIN_BR52 -to i_ddr4_comp1_rzq
set_location_assignment PIN_BR49 -to i_ddr4_comp1_refclk_p
set_location_assignment PIN_CF38 -to o_ddr4_comp1_a[11]
set_location_assignment PIN_CH38 -to o_ddr4_comp1_a[10]
set_location_assignment PIN_CA41 -to o_ddr4_comp1_a[9]
set_location_assignment PIN_CC41 -to o_ddr4_comp1_a[8]
set_location_assignment PIN_CF41 -to o_ddr4_comp1_a[7]
set_location_assignment PIN_CH41 -to o_ddr4_comp1_a[6]
set_location_assignment PIN_CH49 -to o_ddr4_comp1_a[5]
set_location_assignment PIN_CF49 -to o_ddr4_comp1_a[4]
set_location_assignment PIN_CA52 -to o_ddr4_comp1_a[3]
set_location_assignment PIN_CC52 -to o_ddr4_comp1_a[2]
set_location_assignment PIN_CH52 -to o_ddr4_comp1_a[1]
set_location_assignment PIN_CF52 -to o_ddr4_comp1_a[0]
set_location_assignment PIN_CL26 -to o_ddr4_comp1_par
set_location_assignment PIN_CL30 -to o_ddr4_comp1_ck_n
set_location_assignment PIN_CK33 -to o_ddr4_comp1_ck_p
set_location_assignment PIN_CK35 -to o_ddr4_comp1_cke
set_location_assignment PIN_CK39 -to o_ddr4_comp1_odt
set_location_assignment PIN_CL45 -to o_ddr4_comp1_act_n
set_location_assignment PIN_CK48 -to o_ddr4_comp1_cs_n
set_location_assignment PIN_CK45 -to o_ddr4_comp1_reset_n
set_location_assignment PIN_CL42 -to o_ddr4_comp1_bg[1]
set_location_assignment PIN_CK54 -to io_ddr4_comp1_dq[10]
set_location_assignment PIN_CL51 -to io_ddr4_comp1_dq[8]
set_location_assignment PIN_CL54 -to io_ddr4_comp1_dq[12]
set_location_assignment PIN_CK56 -to io_ddr4_comp1_dq[14]
set_location_assignment PIN_CL66 -to io_ddr4_comp1_dqs_n[1]
set_location_assignment PIN_CK63 -to io_ddr4_comp1_dqs_p[1]
set_location_assignment PIN_CL73 -to io_ddr4_comp1_dq[11]
set_location_assignment PIN_CK73 -to io_ddr4_comp1_dq[13]
set_location_assignment PIN_CL70 -to io_ddr4_comp1_dq[15]
set_location_assignment PIN_CK66 -to io_ddr4_comp1_dq[9]

set_location_assignment PIN_CL6   -to io_ddr4_comp1_dq[28]
set_location_assignment PIN_CK8   -to io_ddr4_comp1_dq[24]
set_location_assignment PIN_CL8   -to io_ddr4_comp1_dq[30]
set_location_assignment PIN_CK11  -to io_ddr4_comp1_dq[26]
set_location_assignment PIN_CL17  -to io_ddr4_comp1_dqs_n[3]
set_location_assignment PIN_CK17  -to io_ddr4_comp1_dqs_p[3]
set_location_assignment PIN_CK20  -to io_ddr4_comp1_dq[25]
set_location_assignment PIN_CL20  -to io_ddr4_comp1_dq[27]
set_location_assignment PIN_CK26  -to io_ddr4_comp1_dq[29]
set_location_assignment PIN_CL23  -to io_ddr4_comp1_dq[31]
set_location_assignment PIN_BF46  -to io_ddr4_comp1_dq[22]
set_location_assignment PIN_BE46  -to io_ddr4_comp1_dq[20]
set_location_assignment PIN_BE50  -to io_ddr4_comp1_dq[18]
set_location_assignment PIN_BF50  -to io_ddr4_comp1_dq[16]
set_location_assignment PIN_BE57  -to io_ddr4_comp1_dqs_n[2]
set_location_assignment PIN_BE61  -to io_ddr4_comp1_dqs_p[2]
set_location_assignment PIN_BF64  -to io_ddr4_comp1_dq[17]
set_location_assignment PIN_BE64  -to io_ddr4_comp1_dq[21]
set_location_assignment PIN_BE68  -to io_ddr4_comp1_dq[23]
set_location_assignment PIN_BF68  -to io_ddr4_comp1_dq[19]
set_location_assignment PIN_BM38  -to io_ddr4_comp1_dq[6]
set_location_assignment PIN_BK38  -to io_ddr4_comp1_dq[0]
set_location_assignment PIN_BH41  -to io_ddr4_comp1_dq[2]
set_location_assignment PIN_BH38  -to io_ddr4_comp1_dq[4]
set_location_assignment PIN_BM49  -to io_ddr4_comp1_dqs_n[0]
set_location_assignment PIN_BK49  -to io_ddr4_comp1_dqs_p[0]
set_location_assignment PIN_BH52  -to io_ddr4_comp1_dq[3]
set_location_assignment PIN_BH49  -to io_ddr4_comp1_dq[1]
set_location_assignment PIN_BP52  -to io_ddr4_comp1_dq[5]
set_location_assignment PIN_BM52  -to io_ddr4_comp1_dq[7]

set_instance_assignment -name IO_STANDARD "1.2V TRUE DIFFERENTIAL SIGNALING" -to i_ddr4_comp1_refclk_p -entity top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to i_clk_hvio_6a_100m -entity top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to i_fpga_core_resetn -entity top
